<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */

echo $block->sayHello();
?>

<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}

</style>

<table>
  <tr>
    <th class="post-id">Id</th>
    <th class="post-name">Name</th>
    <th>Content</th>
  </tr>
    <?php
        foreach ($block->getPostCollection() as $key=>$post){
            echo '<tr>
                    <td>'.$post->getPostId().'</td>
                    <td>'.$post->getName().'</td>
                    <td>'.$post->getPostContent().'</td>
                  </tr>';
        }
    ?>
</table>


<?php
$helper = $this->helper('TreeDevs\Crud\Helper\Data');?>
<?php
    echo $helper->getLoadProduct(1);
?>

<?php if($helper->isLoggedIn()): ?>
<div class="box-tocart">
        <p><a href="<?php echo $block->getUrl('customer/account/login') ?>" title="<?php echo __('Login') ?>"><?php echo __('Login') ?></a> or <a href="<?php echo $block->getUrl('customer/account/create') ?>" title="<?php echo "Register" ?>"><?php echo "Register" ?></a></p>
</div>
<?php else: ?>
    <div>not logged in</div>
<?php endif; ?>

<a class="action primary"
   href="<?php echo $block->getUrl('crud/index/insert'); ?>">
    Add Record </a>

</body>
</html>