<section class="featured">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 featured__row">
                <span class="featured__icon">
                    <i class="fas fa-shuttle-van"></i>
                </span>
                <?php if($block->getData('features_title_1')): ?>
                    <h2 class="featured__title"><?php echo $block->getData('features_title_1'); ?></h2>
                <?php endif; ?>
                <?php if($block->getData('features_text_1')): ?>
                    <h2 class="featured__content"><?php echo $block->getData('features_text_1'); ?></h2>
                <?php endif; ?>
            </div>
            <div class="col-md-3 featured__row">
                <span class="featured__icon">
                    <i class="fas fa-shield-alt"></i>
                </span>
                <?php if($block->getData('features_title_2')): ?>
                    <h2 class="featured__title"><?php echo $block->getData('features_title_2'); ?></h2>
                <?php endif; ?>
                <?php if($block->getData('features_text_2')): ?>
                    <h2 class="featured__content"><?php echo $block->getData('features_text_2'); ?></h2>
                <?php endif; ?>
            </div>
            <div class="col-md-3 featured__row">
                <span class="featured__icon">
                    <i class="far fa-comments"></i>
                </span>
                <?php if($block->getData('features_title_3')): ?>
                    <h2 class="featured__title"><?php echo $block->getData('features_title_3'); ?></h2>
                <?php endif; ?>
                <?php if($block->getData('features_text_3')): ?>
                    <h2 class="featured__content"><?php echo $block->getData('features_text_3'); ?></h2>
                <?php endif; ?>
            </div>
            <div class="col-md-3 featured__row">
                <span class="featured__icon">
                    <i class="far fa-credit-card"></i>
                </span>
                <?php if($block->getData('features_title_4')): ?>
                    <h2 class="featured__title"><?php echo $block->getData('features_title_4'); ?></h2>
                <?php endif; ?>
                <?php if($block->getData('features_text_4')): ?>
                    <h2 class="featured__content"><?php echo $block->getData('features_text_4'); ?></h2>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>